# Generated by Django 4.2.28 on 2026-02-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('declined', 'Declined'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
